%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\SATIMO\Desktop\BDAerismann\BDA\Effizienz3oder5.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/12/30 11:21:21

%% Initialize variables.
filename = 'C:\Users\SATIMO\Desktop\BDAerismann\BDA\Effizienz3oder5.txt';
delimiter = '\t';
startRow = 3;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Frequency = dataArray{:, 1};
Efficiency = dataArray{:, 2};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

plot(Frequency,Efficiency)
grid on
legend('efficiency')
